[project]
name = "superspinsim"
version = "1.0.0"
description = "A GPU-based simulator for time-dependent quantum systems."
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
	"numba",
	"cuda-core",
	"cuda-bindings",
	"numba-cuda",
	"numpy",
	"sympy",
	"qutip"
]

[tool.setuptools.packages.find]
exclude = [
	"build*",
	"docs*",
	"test*",
	"examples*"
]
