[project]
name = "superspinsim"
version = "0.2.0"
description = "Fast integrator for the Lindblad master equation"
authors = [
    {name = "Alex Tritt", email = "alex.tritt@monash.edu"}
]
license = "BSD-3"
readme = "README.md"

requires-python = ">=3.11,<3.14"
requires = [
    "numba",
    "numpy",
    "qutip"
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numba="<0.61.0"
numpy=">0"
qutip=">0"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
